apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: apps
  name: apps
spec:
  ports:
    - name: "1113"
      port: 1113
      targetPort: 80
  selector:
    io.kompose.service: apps
