# Stage 1: Python builder
FROM python:3.14-alpine

WORKDIR /opt/app

COPY requirements.txt /tmp/requirements.txt

WORKDIR /opt/app/./lightdock

WORKDIR /opt/app

RUN apk update && \
    xargs apk add --no-cache < /tmp/requirements.txt && \
    rm /tmp/requirements.txt

RUN yarn install && \
    yarn add express cors fs nodemon cookie-parser bcrypt

WORKDIR /etc/nginx

COPY ./html /etc/nginx/html

# Set the working directory
WORKDIR /opt/app

# Copy the application files into the container
COPY ./Markov .

WORKDIR /opt/app/./MarkovProprietary/pipelinestages/app/mount

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile --production

WORKDIR /opt/app/MarkovProprietary

# Set path variables
ENV PYTHONPATH=""
ENV MARKOV_HOME=/opt/app/MarkovProprietary/pipelinestages
ENV LIGHTDOCK_HOME=/opt/app/lightdock
ENV GEMMI_HOME=/opt/app/gemmi
ENV PATH=$PATH:$LIGHTDOCK_HOME/bin:$MARKOV_HOME/bin:$GEMMI_HOME/bin
ENV PYTHONPATH=$PYTHONPATH:$LIGHTDOCK_HOME:$MARKOV_HOME:$GEMMI_HOME:/usr/local/lib/python3.12/site-packages

WORKDIR /opt/app/./lightdock

# Create necessary directories
RUN mkdir -p /opt/app/lightdock/mount/input && \
    touch /opt/app/lightdock/mount/input/message.txt

# Set execution permissions for scripts
RUN chmod u+x run_server_one.sh run_lightdock.sh run_server_two.sh renew.sh

# Unzip files
RUN cd ../MarkovProprietary/pipelinestages/make_tables/python && python unzip.py

# Copy supervisord.conf into the container
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN pip install flask flask_cors gunicorn jwt

EXPOSE 8888 4000 8000 0000

CMD ["/bin/sh", "./run_flask.sh"]
