apiVersion: v1
data:
  localhost_2-key.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDnQkDvK27j4lI+
    /MMx+ZdjhGy8KTiQOHAWvhFjNTYWUIe8jLcU7OJoE4lgax1axGyyxRi0hlB7g8Uk
    Q9HyalRRuVC5GRB2owBAU6TrnUI6OnSAOGqaqwc1M/AWlffbOiW9MdWwclMwnUQh
    Abd8ACEuWV/fiNaVMweRz8zjSs11lvKbn/QIGS4/mqKuOs4jJGnuA/DC1Fy6/Fw+
    uHzuDoEDbchn6FKDHjKvpQxyxLwTTHVRKcu9wyFIs9ZCZawpUVSMHBw3Sn21+eVq
    lqE3m+1f1kgunfZpO6AhHqj4InI5hXdn0CGG1KqoM0q+u6xAtCerXaQgFT/PKX/6
    gcKQnWu9AgMBAAECggEBAKsOWrGOUuvFEEj+9fMVR2GZJkTXyLsExAROetYDGgrP
    bleNTi7wOVf6e3cSRBhLiouBNpDxeL6j7UKx162T8OKyTH9dhsv6LclnFWoiXEZt
    zpa5JEFbmG1GCaTrMPa7wAZ9wi5NojMnYKl5d5sFDYYXHc9ejDq4EDVOm6LURb1f
    jghVcftGuqAPxatWtimUa5YPJQR2GJfjvkv/7VFSNHQD2lIJNZhg1FEiGlD0L3Bn
    Hxwlof38scjCTcMggb8aVhYtUnN+fg86wiysnPSbgKjnPBEtkXv0SkN/gL9zVRpA
    ur2bzK5gv5X5K9TdQkWgH+Tt9IULKb8oUNIymuLKf4ECgYEA8tISaocog9KOVgpa
    gSG97c1xVZIvWAjFdtc6xveO3z5OzpJtB/7uSMAxSt9e6kCBk+ls3o6AlseMXEZ/
    ulE2ivvi0VCcZyT269JAttlj8kKSwKhUKMaNTArpLpJRmrvsyow0V8m0oG1Di+nG
    5Hkp3ZnfbA+HuNu3UHhurPaFtbUCgYEA88+In8kYbpE93jAtxnHp2RSJ7d7xNN6C
    ZwAey1rRejxM2DdEM7cgBmZjSE8HGSJqeUojuZonUEeMinP5sN6GnkyLzI4U48aO
    Z/he/XqLGLpR+RWQEXotWwmhgRQQ6FFlRpBUsbWeXxID/mH+kLcoE5WXhInOMZPD
    5Iwh7cFFIukCgYA4/eFgq3Rw7DyIKUnwwRCo/e053mPKT9S4/e9Hv9cCwscQaQG6
    PLWE0cdAAYlvhdBj/QeWfO/lc9SX29wiyOj6WgB0jG0JMH3b/688u21f8Qwst9V4
    9JE5Zd4xFhqdLLp5F8s5R5hjhwGxlx8dhOq0nmb4H/UFCFzQQFQJuJrNeQKBgCEF
    Po/FgJWY/jQVel2iF/XankOlKi3q5OZmUcVg63YOrKmr8oS+jIvRWij06xUwYBNF
    Q0lj42cwCYzG4E5gFQNjgpuVsqaWwbq7HMJf0m7q7Sc7EGQNlA78Yu9EdHXCcGD6
    Mz5ORsDBg+D0DLI03Cyq2faNY2u7g5B0mjPFNUPhAoGAcE2Yr7t5Us08O4sPigLQ
    Gq4N08PB3XtbrusIAi2gkHZeoezwtHEViobeAOJMjQj7/fwevcMsd4Ca6e5kgnip
    CDj382U8VPgQuZUjf76uBro33vZrOmq9DVNiIZWn1w3Y9JRsmlBGr4jzkwXTiP9D
    Z45Wj/Nvc+c3yZA3VAlxxes=
    -----END PRIVATE KEY-----
  localhost_2.pem: |
    -----BEGIN CERTIFICATE-----
    MIIEgDCCAuigAwIBAgIRAL7TBQotPqmqbpCAWHphi+UwDQYJKoZIhvcNAQELBQAw
    gZsxHjAcBgNVBAoTFW1rY2VydCBkZXZlbG9wbWVudCBDQTE4MDYGA1UECwwvamFt
    ZXNASmFtZXNzLU1hY0Jvb2stUHJvLmxvY2FsIChKYW1lcyBKZW5uaW5ncykxPzA9
    BgNVBAMMNm1rY2VydCBqYW1lc0BKYW1lc3MtTWFjQm9vay1Qcm8ubG9jYWwgKEph
    bWVzIEplbm5pbmdzKTAeFw0yNTA5MTcyMjQ1MjBaFw0yNzEyMTcyMzQ1MjBaMGMx
    JzAlBgNVBAoTHm1rY2VydCBkZXZlbG9wbWVudCBjZXJ0aWZpY2F0ZTE4MDYGA1UE
    CwwvamFtZXNASmFtZXNzLU1hY0Jvb2stUHJvLmxvY2FsIChKYW1lcyBKZW5uaW5n
    cykwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDnQkDvK27j4lI+/MMx
    +ZdjhGy8KTiQOHAWvhFjNTYWUIe8jLcU7OJoE4lgax1axGyyxRi0hlB7g8UkQ9Hy
    alRRuVC5GRB2owBAU6TrnUI6OnSAOGqaqwc1M/AWlffbOiW9MdWwclMwnUQhAbd8
    ACEuWV/fiNaVMweRz8zjSs11lvKbn/QIGS4/mqKuOs4jJGnuA/DC1Fy6/Fw+uHzu
    DoEDbchn6FKDHjKvpQxyxLwTTHVRKcu9wyFIs9ZCZawpUVSMHBw3Sn21+eVqlqE3
    m+1f1kgunfZpO6AhHqj4InI5hXdn0CGG1KqoM0q+u6xAtCerXaQgFT/PKX/6gcKQ
    nWu9AgMBAAGjdjB0MA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcD
    ATAfBgNVHSMEGDAWgBRTWduSdbsQNLL7QUh/gZU6IJciJTAsBgNVHREEJTAjggls
    b2NhbGhvc3SHBH8AAAGHEAAAAAAAAAAAAAAAAAAAAAEwDQYJKoZIhvcNAQELBQAD
    ggGBAKhgzi4iMOL7bO2UueOEatUAiw6sZbH7XELLn4NWzbHQcuzVWbCdTKPlHAyj
    14d871ZbML+pJYJzV9KaG0h/hEaDYQS7o5B8sr8qOFDHDm/O+v0txelvYy1F2f68
    YOPtdSpQo25OVa9VN9es7klkHjqTghOu9bOWjO/EhGjca1/t1Zzdr597B58wbX3U
    LEqzclGfKxB9lflNjPY5NRl+dmYxsPttZcY8gcLtVyVYJHKaiWZQpqdYoWgF2i8d
    BnlmwKLZHFaM86inl4swrR+DRd9NoxoUXGzOdkx8yOytZQiGgEDWPw0kmXfgnDm7
    6GmZ7D7Hcjdbr+LvaQA5SFTc0e1TeB8Ouvc/Ng40BHfUjsgKTbsSEEsi61tkG4WE
    nAkQbqJ0jwkNtoCwUM3GtLflcxRVyEO+8mJ3t+fjGJHQbSGnJiSnFzGQ8xp5DgAq
    JtdyV80bRQjuT1MCSO9Nzq8YYABtaEws3WeYC6Q9f8FyhUA9EU0P12SrYRiNTBkD
    CzDG1g==
    -----END CERTIFICATE-----
  privkey.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDDATNcgt/jY0ay
    xj8zWrojaKDayZ9BJqUTkPunMMGB/m17WIl7EYv72YRElCL2D5pwRk4mePa3MlS8
    TxmmIN/GpJBIt8GFaLcwmC5+54xcpDrfFVZl4jHQlXKEYhr82yUJe8sjRkXt7qzA
    uVfXzHXs4cD9RShBkhJxQiWnCw/W6EHa+mYRRdFmXZJsdCqNMDZEkU8WN55TXQLK
    TB1FWL4ItH/NPWnFU7B32o9aG4rLK/wqo2hQ5UtbLjT43rYlcPjlIcR1vRi/6BNA
    OloSvsvxFfrjmntFmehFzFPOZLG4ApQAQPF4RwCfL0xd50P8zWK34k71I5zmkHHE
    r9Kg3TWvAgMBAAECggEAG6zO8kEsryPGw9Z437vvkNjng0V8EY3/fZBk9qxnuiA2
    v3uoP0wVNs//ApCXiZ5bR7Xin3kpYoSFHBiJxlcCCzoNtBRIJbvfy8i9SItqEzfH
    lyN7GIiKk1SyZPFbbSlYz0i/Yqk1gXgPEmb7fYfp8I11izxGY0/syCAgId3jCJe8
    SzJy39x6sW3HuQWyL9CzgModPH7wuUCwjn+4ApuJVaOlt6TwLhyhH1Rs9ZSfCWH2
    I8JoagvsksCMaKzbtGzl4S02vkEtYhYxENga2ht8SQtIcSEP3aEGSHkT/PyNctXF
    eiPUDNdxlHcwBncU16Liug5Ft8GFjUYayHOi9mAJGQKBgQDqT64n8G7o8+o3d9Bw
    hJFoORryp9cUX+L+T8xebadhfmdEdI1sV5gByhkice+ogxk0dK7S2ncIKH/5qUDG
    2AGI5Mz03/x8FCM4IRLTNVJrSy44yBV6R5OtZlc3D8vsOnGJ3cvK6orUG5/fVyF4
    OSSUC0OLoo3CtUTWac+NVZLFywKBgQDVDhk9KAqABhp58/erPT/IlN9PHszzFk9/
    j2/nu+8ERCTKE9UDs+WYRn+Nfr0jYCEbD5Xzqhx/15K0DWMUAvdswFz1zYSerEau
    nVHBwqIe9h80n4m16mASCozMNS61tWgTTXELV3G80wc5WJkr1J8i7TgFvK75IpRZ
    3DoY7NszLQKBgHacz3S4aezTTQW3SXUsJs+z2Mht3psZzzcd/j7vE4RvEKe+uLjX
    vsNpI0AknUWY1/GN/9INdaRTnDUuUPRX9K7v5DEyEgZdy1Zmp7jzjT1zWXq1DupP
    wZpN7GibPoffLgq0lK2r/YtSUKQm33KUuseWzCKrr0eZq7c+6SqK3znxAoGAfFxE
    YywyJNRrM/AyCuQvjPdI+bfyzZmiQcUJ/uv18jmMd9/noMerJp1P6tmlsTZ1XIRW
    dOpAxGainTKLOK0am4IVQOz7klrgzx/JDx563zOut1rAWU07UoyR7sjEQRBodYvo
    hkQ+gYd0WgbbMXhkg1CQONkQESAcE++2gcIPmOkCgYB7J3nsi9E9oXRpO98iqfPO
    O3hMGqcSf5Fy6oqKwZpMRNj0VslUb5oBL6eube20VvIPkDIrmUQlswp3DtNNHTFO
    jTScBECduz4VED+aZD6FFbqdOcwjmZmYMRe25P0V/AdHYoj85ogFJN5QrZ5aAYgY
    kVds1z47kTJbUWdpkRLPdg==
    -----END PRIVATE KEY-----
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: healthapp
  name: healthapp-cm0
