apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: login
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: login
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: login
    spec:
      containers:
        - env:
            - name: JWT_SECRET
              value: d3bbfd8f0662c7dc7b48786722ce7aaa8e658ed4628f767ee448a8fab8e3bf61a9fb8fad863fec7476d51fc7822933d0d356812a41f71371f55bfc628050d84f
          image: us-central1-docker.pkg.dev/project-05da6024-aca6-464e-bd3/markov-repo/login
          name: login
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/tor/my_service
              name: tor-keys
      restartPolicy: Always
      volumes:
        - name: tor-keys
          persistentVolumeClaim:
            claimName: tor-keys
