apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: login
  name: login
spec:
  ports:
    - name: "1112"
      port: 1112
      targetPort: 80
  selector:
    io.kompose.service: login
