apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: markov-app
  name: markov-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: filestore-rwx
  resources:
    requests:
      storage: 12Gi
