apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-rwx-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Ti
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: shared-rwx/us-east1-b/shared_data
    volumeAttributes:
      ip: 172.29.111.106
      volume: shared_data
      tier: standard
  persistentVolumeReclaimPolicy: Retain
  storageClassName: filestore-rwx
  volumeMode: Filesystem
