apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulatorapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulatorapp
  template:
    metadata:
      labels:
        app: simulatorapp
    spec:
      containers:
      - name: simulatorapp
        image: us-central1-docker.pkg.dev/project-05da6024-aca6-464e-bd3/markov-repo/simulatorapp:v59
        # Add your ports, environment variables, or resource limits here
