apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
      - name: simulator
        image: us-central1-docker.pkg.dev/project-05da6024-aca6-464e-bd3/markov-repo/simulatorapp:v57
        imagePullPolicy: Always
        ports:
        - containerPort: 80
