[supervisord]
nodaemon=true

# Keep all services alive for 8 hours
[program:keep_alive]
command=/bin/bash -c "sleep 28800"  # Sleep for 8 hours
autostart=true
autorestart=false

# nginx server
[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autorestart=true
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log

# receive_signal.py
[program:gunicorn]
directory=/opt/app/MarkovProprietary/pipelinestages/app/mount
command=/usr/local/bin/gunicorn -w 4 -b 0.0.0.0:8000 receive_signal:app --timeout 7000
autostart=true
autorestart=true
stderr_logfile=/var/log/gunicorn.err.log
stdout_logfile=/var/log/gunicorn.out.log

# server_one.js
[program:run_server_one]
command=/usr/bin/bash ./run_server_one.sh
autostart=true
autorestart=true
stderr_logfile=/var/log/run_server_one.err.log
stdout_logfile=/var/log/run_server_one.out.log

# server_two.js
[program:monitor_server_two]
command=/usr/bin/bash ./run_server_two.sh
autostart=true
autorestart=true
stderr_logfile=/var/log/run_server_two.err.log
stdout_logfile=/var/log/run_server_two.out.log

# server_health.sh
[program:run_health_app]
command=/usr/bin/bash /opt/app/lightdock/server_health.sh
autostart=true
autorestart=true
stderr_logfile=/var/log/server_health.err.log
stdout_logfile=/var/log/server_health.out.log

# Run_Markov.py
[program:Run_Markov]
command=/usr/local/bin/python /opt/app/lightdock/Run_Markov.py
autostart=true
autorestart=true
stderr_logfile=/var/log/Run_Markov.err.log
stdout_logfile=/var/log/Run_Markov.out.log