apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: viewer
  name: viewer
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 80
  selector:
    io.kompose.service: viewer
